######################################################################
# Automatically generated by qmake (3.1) Thu Aug 8 17:15:44 2024
######################################################################

TEMPLATE = app
TARGET = HGTNucleicAcidExtraction
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += AXEMgr.h \
           AXEProcessItem.h \
           AXEProcessItem_Icon.h \
           ChooseItemListDialog.h \
           MainWindow.h \
           PlayView.h \
           ProcessParamsDialog.h \
           ProcessView.h \
           SettingView.h \
           UVView.h \
           Common/BaseDialog.h \
           Common/BasePageContent.h \
           Common/BaseUI.h \
           Common/BaseView.h \
           Common/BaseWidget.h \
           Common/ConnectDatabase.h \
           Common/GlobalDefine.h \
           Common/HButtonIcon.h \
           Common/HLineEdit.h \
           Common/HMessageBox.h \
           Common/HTableView.h \
           Common/HTableViewItemModel.h \
           Common/IBaseView.h \
           Common/imagewidget.h \
           Common/PopDialog.h \
           Common/Singleton.h \
           Common/UIUtility.h \
           Common/Utility.h \
           /../../Sln_CommonLibrary/HGTSoftKeyboardService/SoftKeyboardService.h \
           ../../Sln_CommonLibrary/public/IFSoftKeyboardService.h
SOURCES += AXEMgr.cpp \
           AXEProcessItem.cpp \
           AXEProcessItem_Icon.cpp \
           ChooseItemListDialog.cpp \
           main.cpp \
           MainWindow.cpp \
           PlayView.cpp \
           ProcessParamsDialog.cpp \
           ProcessView.cpp \
           SettingView.cpp \
           UVView.cpp \
           Common/BaseDialog.cpp \
           Common/BasePageContent.cpp \
           Common/BaseUI.cpp \
           Common/BaseView.cpp \
           Common/BaseWidget.cpp \
           Common/ConnectDatabase.cpp \
           Common/HLineEdit.cpp \
           Common/HMessageBox.cpp \
           Common/HTableView.cpp \
           Common/HTableViewItemModel.cpp \
           Common/IBaseView.cpp \
           Common/PopDialog.cpp \
           Common/UIUtility.cpp \
           Common/Utility.cpp
